### ISSUE TITLE
New Feature : Tzatziki-front Module

### ISSUE THREAD

**Issue by CGUYOT26** [Decathlon/tzatziki#156]
In our project, we use Playwright to test our front components.
Playwright is linked to Cucumber to make search in DOM, make actions or fill forms.
We need to create a module to enable this front behaviours.
```[tasklist]
### Tasks
- [ ] https://github.com/Decathlon/tzatziki/issues/168
- [ ] https://github.com/Decathlon/tzatziki/issues/169
- [ ] https://github.com/Decathlon/tzatziki/issues/171
- [ ] https://github.com/Decathlon/tzatziki/issues/170
```
