### ISSUE TITLE
[Tzatziki Front] module chore initialization

### ISSUE THREAD

**Issue by alexandrepa** [Decathlon/tzatziki#253]
Implementation of the basic front module principles. A parent module with interfaces definitions, generic browser configuration definition and parallelism handling. 
```[tasklist]
### Tasks
- [ ] https://github.com/Decathlon/tzatziki/issues/254
- [ ] https://github.com/Decathlon/tzatziki/issues/255
- [ ] https://github.com/Decathlon/tzatziki/issues/256
```
