### ISSUE TITLE
[Tzatziki Front] Create Gherkins Steps

### ISSUE THREAD

**Issue by alexandrepa** [Decathlon/tzatziki#257]
We want to propose  generic gherkins steps that can be used to manipulate and assert on the browser so user don't have the need to create custom steps that manipulate directly the browser interface.
```[tasklist]
### Tasks
- [ ] https://github.com/Decathlon/tzatziki/issues/258
- [ ] https://github.com/Decathlon/tzatziki/issues/259
- [ ] https://github.com/Decathlon/tzatziki/issues/260
```
